version: '3.4'

services:
  app: 
    container_name: regulation_lib_app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - project_dir:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules

  database:
    container_name: regulation_lib_db
    image: postgres:12.1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # './init.sql' копируется в папку образа PostgreSQL, в нем он запускается автоматически

volumes:
  project_dir:
    driver_opts:
      type: 'none'
      device: '/home/dan/staff/regulation_lib'
      o: 'bind'
  gem_cache:
  node_modules:
