version: '3.4'

services:
  db:
    container_name: regulation_lib_db
    image: postgres:12.1
    ports:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # './init.sql' копируется в папку образа PostgreSQL, в нем он запускается автоматически

  app: 
    container_name: regulation_lib_app
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules

volumes:
  db_data:
  gem_cache:
  node_modules:
