default: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: postgres
  password:
  host: db
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: myapp_development_test


production:
  <<: *default
  database: myapp_development_production
