default: &default
  adapter: postgresql
  encoding: unicode
  database: regulation_lib
  username: regulation_lib
  port: 5432
  host: regulation_lib_db
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: regulation_lib_test


production:
  <<: *default
  database: regulation_lib_production
